name        : gstreamer-0.10
version     : 0.10.36
release     : 1
source      :
    - http://gstreamer.freedesktop.org/src/gstreamer/gstreamer-0.10.36.tar.gz : 7d869babaf35c2dbfc13dd44b4eec92cd21cd37b940d9147c6a5ed8e3fbab3eb
license     :
    - LGPL-2.0
summary     : Streaming media framework
builddeps   :
    - pkgconfig(zlib)
    - pkgconfig(libffi)
    - pkgconfig(libxml-2.0)
    - pkgconfig(libpcre)
description : |
    GStreamer is a streaming media framework that enables applications to share a common set of plugins for things like video encoding and decoding, audio encoding and decoding, audio and video filters, audio visualisation, web streaming and anything else that streams in real-time or otherwise. This package only provides base functionality and libraries. You may need at least gst-plugins-base-1.0.6 and one of Good, Bad, Ugly or Libav plugins.
patterns    :
    - devel : /usr/share/aclocal
setup       : |
    %configure --disable-static \
               --libexecdir=/usr/lib \
               --with-package-name="GStreamer 0.10.36 Solus" \
               --with-package-origin=https://solus-project.com \
build       : |
    %make
install     : |
    %make_install
